name: Build and Deploy to Production 🚀

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build PWA 🛠️

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✈️
        uses: actions/checkout@v2

      - name: Use Node.js 14.x ⚙️
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies 🔧
        run: |
          npm install -g @quasar/cli
          npm ci

      - name: Set Environment Variables
        run: printenv > .env
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Build PWA 🛠️
        run: quasar build -m pwa

      - name: Archive Production Artifact 🗃️
        uses: actions/upload-artifact@v2
        with:
          name: pwa
          path: dist/pwa

  deploy:
    name: Deploy 🚀

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✈️
        uses: actions/checkout@v2

      - name: Download Artifact 🗃️
        uses: actions/download-artifact@v2
        with:
          name: pwa
          path: dist/pwa

      - name: Deploy to Firebase 🚀
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
